server:
  port: 8080
spring:
  application:
    name: reggie                                             #应用名

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                        #将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射实体或属性
